// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: desc/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoReq) Reset() {
	*x = UserInfoReq{}
	mi := &file_desc_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReq) ProtoMessage() {}

func (x *UserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReq.ProtoReflect.Descriptor instead.
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return file_desc_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResp) Reset() {
	*x = UserInfoResp{}
	mi := &file_desc_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResp) ProtoMessage() {}

func (x *UserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResp.ProtoReflect.Descriptor instead.
func (*UserInfoResp) Descriptor() ([]byte, []int) {
	return file_desc_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfoResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_desc_user_user_proto protoreflect.FileDescriptor

const file_desc_user_user_proto_rawDesc = "" +
	"\n" +
	"\x14desc/user/user.proto\x12\x04user\"!\n" +
	"\vUserInfoReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\"\n" +
	"\fUserInfoResp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2:\n" +
	"\x04user\x122\n" +
	"\tuser_info\x12\x11.user.UserInfoReq\x1a\x12.user.UserInfoRespB\bZ\x06./userb\x06proto3"

var (
	file_desc_user_user_proto_rawDescOnce sync.Once
	file_desc_user_user_proto_rawDescData []byte
)

func file_desc_user_user_proto_rawDescGZIP() []byte {
	file_desc_user_user_proto_rawDescOnce.Do(func() {
		file_desc_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desc_user_user_proto_rawDesc), len(file_desc_user_user_proto_rawDesc)))
	})
	return file_desc_user_user_proto_rawDescData
}

var file_desc_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_desc_user_user_proto_goTypes = []any{
	(*UserInfoReq)(nil),  // 0: user.UserInfoReq
	(*UserInfoResp)(nil), // 1: user.UserInfoResp
}
var file_desc_user_user_proto_depIdxs = []int32{
	0, // 0: user.user.user_info:input_type -> user.UserInfoReq
	1, // 1: user.user.user_info:output_type -> user.UserInfoResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_desc_user_user_proto_init() }
func file_desc_user_user_proto_init() {
	if File_desc_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desc_user_user_proto_rawDesc), len(file_desc_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_desc_user_user_proto_goTypes,
		DependencyIndexes: file_desc_user_user_proto_depIdxs,
		MessageInfos:      file_desc_user_user_proto_msgTypes,
	}.Build()
	File_desc_user_user_proto = out.File
	file_desc_user_user_proto_goTypes = nil
	file_desc_user_user_proto_depIdxs = nil
}
