name: CI/CD Pipeline

env:
  REGISTRY: ccr.ccs.tencentyun.com
  NAMESPACE: ${{ secrets.TENCENT_NAMESPACE }}
  USER_IMAGE_NAME: ${{ github.event.repository.name }}-user

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Tencent Cloud CCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
        #  username: ${{ secrets.TENCENT_CLOUD_USERNAME }}
         # password: ${{ secrets.TENCENT_CLOUD_PASSWORD }}
          username: 100032858376
          password: 15059775613w

      - name: Read version
        id: version
        run: echo "VERSION=$(cat version)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push user RPC service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./user/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.USER_IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
